services:
  _defaults:
    public: false
    autowire: true

  Domain\Command\:
    resource: '%kernel.project_dir%/src/Domain/Command/**/Handler.php'
    tags:
      - messenger.message_handler

  Domain\Event\:
    resource: '%kernel.project_dir%/src/Domain/Event/**/Handler.php'
    tags:
      - messenger.message_handler

  Domain\Query\:
    resource: '%kernel.project_dir%/src/Domain/Query/**/Handler.php'
    tags:
      - messenger.message_handler
