---
services:
  _defaults:
    public: false
    autowire: true

  ### APPLICATION ###

  Application\:
    resource: '%kernel.project_dir%/src/Application/*'

  Application\Controller\:
    resource: '%kernel.project_dir%/src/Application/Controller/*'
    tags:
      - controller.service_arguments

  ### DOMAIN ###

  Domain\Collection\:
    resource: '%kernel.project_dir%/src/Domain/Collection/*'
    exclude:
      - '%kernel.project_dir%/src/*Exception.php'

  Domain\Message\:
    resource: '%kernel.project_dir%/src/Domain/Message/**/Handler.php'
    exclude:
      - '%kernel.project_dir%/src/*Exception.php'
    tags:
      - messenger.message_handler

  ### INFRASTRUCTURE ###

  Infrastructure\:
    resource: '%kernel.project_dir%/src/Infrastructure/*'
    exclude:
      - '%kernel.project_dir%/src/Infrastructure/Doctrine/Entity/*'

  Infrastructure\Doctrine\Repository\:
    resource: '%kernel.project_dir%/src/Infrastructure/Doctrine/Repository/*'
    tags:
      - doctrine.repository_service
