---
services:
  _defaults:
    public: false
    autowire: true

  ### APPLICATION ###

  Application\:
    resource: '%kernel.project_dir%/src/Application/*'
    exclude:
      - '%kernel.project_dir%/src/Application/Controller/*'

  Application\Controller\:
    resource: '%kernel.project_dir%/src/Application/Controller/*'
    tags:
      - controller.service_arguments

  ### DOMAIN ###

  Domain\Collection\:
    resource: '%kernel.project_dir%/src/Domain/Collection/*'

  Domain\Factory\:
    resource: '%kernel.project_dir%/src/Domain/Factory/*'

  Domain\Message\:
    resource: '%kernel.project_dir%/src/Domain/Message/*'
    exclude:
      - '%kernel.project_dir%/src/Domain/Message/**/Input.php'
      - '%kernel.project_dir%/src/Domain/Message/**/Output.php'
    tags:
      - messenger.message_handler

  ### INFRASTRUCTURE ###

  Infrastructure\:
    resource: '%kernel.project_dir%/src/Infrastructure/*'
    exclude:
      - '%kernel.project_dir%/src/Infrastructure/Doctrine/Entity/*'
      - '%kernel.project_dir%/src/Infrastructure/Symfony/Kernel.php'
