version: 2
updates:
  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: daily
      time: '06:00'
      timezone: UTC
    versioning-strategy: increase

  - package-ecosystem: composer
    directory: /apps/api
    schedule:
      interval: daily
      time: '06:00'
      timezone: UTC
    versioning-strategy: increase

  ### DOCKERFILES ###

  - directory: /apps/api
    package-ecosystem: docker
    schedule:
      interval: daily
      time: '06:00'
      timezone: UTC

  - directory: /apps/mysql
    package-ecosystem: docker
    schedule:
      interval: daily
      time: '06:00'
      timezone: UTC

  - directory: /apps/nginx
    package-ecosystem: docker
    schedule:
      interval: daily
      time: '06:00'
      timezone: UTC

  - directory: /apps/traefik
    package-ecosystem: docker
    schedule:
      interval: daily
      time: '06:00'
      timezone: UTC

  - directory: /apps/web
    package-ecosystem: docker
    schedule:
      interval: daily
      time: '06:00'
      timezone: UTC