version: 2
updates:
  - package-ecosystem: github-actions
    directory: ./
    schedule:
      interval: daily
      time: '06:00'
      timezone: Europe/Paris

  - package-ecosystem: composer
    directory: /apps/api
    schedule:
      interval: daily
      time: '06:00'
      timezone: Europe/Paris
    versioning-strategy: increase
    groups:
      symfony:
        patterns:
          - symfony/*
      doctrine:
        patterns:
          - doctrine/*

  - package-ecosystem: composer
    directory: /tools/rector
    schedule:
      interval: daily
      time: '06:00'
      timezone: Europe/Paris
    versioning-strategy: increase

  ### DOCKERFILES ###

  - directory: /apps/api
    package-ecosystem: docker
    schedule:
      interval: daily
      time: '06:00'
      timezone: Europe/Paris

  - directory: /apps/web
    package-ecosystem: docker
    schedule:
      interval: daily
      time: '06:00'
      timezone: Europe/Paris

  - directory: /services/mysql
    package-ecosystem: docker
    schedule:
      interval: daily
      time: '06:00'
      timezone: Europe/Paris

  - directory: /services/nginx
    package-ecosystem: docker
    schedule:
      interval: daily
      time: '06:00'
      timezone: Europe/Paris

  - directory: /services/rabbitmq
    package-ecosystem: docker
    schedule:
      interval: daily
      time: '06:00'
      timezone: Europe/Paris

  - directory: /services/traefik
    package-ecosystem: docker
    schedule:
      interval: daily
      time: '06:00'
      timezone: Europe/Paris

  - directory: /tools/rector
    package-ecosystem: docker
    schedule:
      interval: daily
      time: '06:00'
      timezone: Europe/Paris
