version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Paris"
    target-branch: "develop"
    commit-message:
      prefix: chore
      prefix-development: chore(dev)
    versioning-strategy: "increase"
  
  - package-ecosystem: "composer"
    directory: "/apps/api"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Paris"
    target-branch: "develop"
    commit-message:
      prefix: chore
      prefix-development: chore(dev)
    versioning-strategy: "increase"
