version: 2
updates:
  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      day: monday
      interval: weekly
      time: '06:00'
      timezone: Europe/Paris
    versioning-strategy: increase
    groups:
      next:
        patterns:
          - '@types/react*'
          - next
          - react*
      eslint:
        patterns:
          - 'eslint*'

  - package-ecosystem: composer
    directory: /apps/api
    schedule:
      day: monday
      interval: weekly
      time: '06:00'
      timezone: Europe/Paris
    versioning-strategy: increase
    groups:
      symfony:
        patterns:
          - symfony/*
      doctrine:
        patterns:
          - doctrine/*

  - package-ecosystem: composer
    directory: /tools/cs-fixer
    schedule:
      day: monday
      interval: weekly
      time: '06:00'
      timezone: Europe/Paris
    versioning-strategy: increase

  - package-ecosystem: composer
    directory: /tools/deptrac
    schedule:
      day: monday
      interval: weekly
      time: '06:00'
      timezone: Europe/Paris
    versioning-strategy: increase

  - package-ecosystem: composer
    directory: /tools/phpstan
    schedule:
      day: monday
      interval: weekly
      time: '06:00'
      timezone: Europe/Paris
    versioning-strategy: increase

  ### DOCKERFILES ###

  - directory: /apps/api
    package-ecosystem: docker
    schedule:
      day: monday
      interval: weekly
      time: '06:00'
      timezone: Europe/Paris

  - directory: /apps/web
    package-ecosystem: docker
    schedule:
      day: monday
      interval: weekly
      time: '06:00'
      timezone: Europe/Paris

  - directory: /services/mysql
    package-ecosystem: docker
    schedule:
      day: monday
      interval: weekly
      time: '06:00'
      timezone: Europe/Paris

  - directory: /services/nginx
    package-ecosystem: docker
    schedule:
      day: monday
      interval: weekly
      time: '06:00'
      timezone: Europe/Paris

  - directory: /services/traefik
    package-ecosystem: docker
    schedule:
      day: monday
      interval: weekly
      time: '06:00'
      timezone: Europe/Paris

  - directory: /tools/cs-fixer
    package-ecosystem: docker
    schedule:
      day: monday
      interval: weekly
      time: '06:00'
      timezone: Europe/Paris

  - directory: /tools/deptrac
    package-ecosystem: docker
    schedule:
      day: monday
      interval: weekly
      time: '06:00'
      timezone: Europe/Paris

  - directory: /tools/phpstan
    package-ecosystem: docker
    schedule:
      day: monday
      interval: weekly
      time: '06:00'
      timezone: Europe/Paris

  - directory: /tools/rector
    package-ecosystem: docker
    schedule:
      day: monday
      interval: weekly
      time: '06:00'
      timezone: Europe/Paris
