include:
  - docker-compose.services.yml

services:
  node:
    build:
      context: ./apps/web
      target: dev
    volumes:
      - ./apps/web:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node.tls=true"
      - "traefik.http.routers.node.rule=Host(`app.localhost`)"
      - "traefik.http.services.node.loadbalancer.server.port=3000"

  api:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
      target: nginx-dev
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.nginx.rule=Host(`api.app.localhost`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    volumes:
      - ./apps/api:/app:ro

  php:
    build:
      context: ./apps/api
      target: dev
    env_file:
      - ./apps/api/.env
    volumes:
      - ./apps/api:/app
    depends_on:
      database:
        condition: service_healthy
        restart: true
