services:
  symfony:
    build:
      context: apps/api
      dockerfile: Dockerfile
      target: cli
    volumes:
      - ./apps/api:/app
    entrypoint: ["symfony"]

  composer:
    extends: symfony
    entrypoint: ["symfony", "composer"]

  console:
    extends:
      service: symfony
    entrypoint: ["symfony", "console"]

  cs-fixer:
    build:
      context: ./tools/cs-fixer
      dockerfile: Dockerfile
    volumes:
      - ./apps/api:/opt/code
    entrypoint: php-cs-fixer
    command: check

  deptrac:
    build:
      context: ./tools/deptrac
      dockerfile: Dockerfile
    volumes:
      - ./apps/api:/opt/code
    entrypoint: deptrac
    command: --report-uncovered

  phpstan:
    build:
      context: ./tools/phpstan
      dockerfile: Dockerfile
    volumes:
      - ./apps/api:/opt/code
    entrypoint: phpstan

  rector:
    build:
      context: ./tools/rector
      dockerfile: Dockerfile
    volumes:
      - ./apps/api:/opt/code
    entrypoint: rector --config /opt/rector/rector.php
