name: testing

services:
  base:
    build:
      context: ./tools
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./apps/api:/opt/code

  cs-fixer:
    extends: base
    build:
      target: cs-fixer
    volumes:
      - ./apps/api:/opt/code
    entrypoint: php-cs-fixer
    command: check

  deptrac:
    extends: base
    build:
      target: deptrac
    entrypoint: deptrac
    command: --report-uncovered

  phpstan:
    extends: base
    build:
      target: phpstan
    entrypoint: phpstan
    env_file:
      - apps/api/.env

  rector:
    extends: base
    build:
      target: rector
    entrypoint: rector --config /opt/rector/rector.php
