services:
  cs-fixer:
    build:
      context: ./tools
      dockerfile: Dockerfile
      target: cs-fixer
    volumes:
      - ./apps/api:/opt/code
    entrypoint: php-cs-fixer
    command: check

  deptrac:
    extends: cs-fixer
    build:
      target: deptrac
    entrypoint: deptrac
    command: --report-uncovered

  phpstan:
    extends: cs-fixer
    build:
      target: phpstan
    entrypoint: phpstan

  rector:
    extends: cs-fixer
    build:
      target: rector
    entrypoint: rector --config /opt/rector/rector.php
