services:
  composer:
    build:
      context: ./tools
      dockerfile: Dockerfile
      target: base
    env_file:
      - ./apps/api/.env
    volumes:
      - ./apps/api:/opt/code
    entrypoint: composer

  cs-fixer:
    extends: composer
    env_file: []
    build:
      target: cs-fixer
    entrypoint: php-cs-fixer
    command: check

  deptrac:
    extends: composer
    env_file: []
    build:
      target: deptrac
    entrypoint: deptrac
    command: --report-uncovered

  phpstan:
    extends: composer
    env_file: []
    build:
      target: phpstan
    entrypoint: phpstan

  rector:
    extends: composer
    env_file: []
    build:
      target: rector
    entrypoint: rector --config /opt/rector/rector.php
