version: '3'

tasks:
  install:
    desc: Build and start the Docker containers
    aliases:
      - default
    deps:
      - bootstrap
      - ssl

  start:
    desc: Start the Docker containers
    cmds:
      - docker compose up -d

  stop:
    desc: Stop the Docker containers
    cmds:
      - docker compose down

  ssl:
    internal: true
    cmds:
      - mkcert -key-file certs/local-key.pem -cert-file certs/local-cert.pem *.app.localhost app.localhost
      - mkcert -install
    status:
      - test -f certs/local-cert.pem
      - test -f certs/local-key.pem

  bootstrap:
    internal: true
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.tools.yml build
      - docker compose -f docker-compose.yml -f docker-compose.tools.yml pull
      - task: yarn
      - task: composer

  yarn:
    internal: true
    cmds:
      - docker compose run --rm --no-deps web npm install
    sources:
      - ./apps/web/package.json
      - ./apps/web/package-lock.json
    generates:
      - ./apps/web/node_modules/**/*

  composer:
    internal: true
    cmds:
      - docker compose run --rm --no-deps php composer install
    sources:
      - ./apps/api/composer.json
      - ./apps/api/composer.lock
    generates:
      - ./apps/api/vendor/**/*

  phpstan:
    cmds:
      - docker compose -f docker-compose.tools.yml up -d phpstan

  deptrac:
    cmds:
      - docker compose -f docker-compose.tools.yml up -d deptrac

  cs-fixer:
    cmds:
      - docker compose -f docker-compose.tools.yml up -d cs-fixer
