version: '3'

silent: true

includes:
  back: ./tasks/back.yaml
  core: ./tasks/core.yaml
  docker: ./tasks/docker.yaml
  front: ./tasks/front.yaml

tasks:
  default:
    desc: Start development
    deps:
      - install
    cmds:
      - task: docker:start
  
  install:
    desc: Install dependencies
    cmds:
      - task: docker:build
      - task: back:install
      - task: front:install
