version: '3'

silent: true
output: 'prefixed'

includes:
  back: ./tasks/back.yaml
  core: ./tasks/core.yaml
  front: ./tasks/front.yaml

tasks:
  default:
    desc: Start development
    deps:
      - install
    cmds:
      - docker-compose up -d --remove-orphans
  
  install:
    desc: Install dependencies
    cmds:
      - task: back:install
      - task: front:install
