version: '3'

includes:
  php: ./tasks/php.yaml
  node: ./tasks/node.yaml

tasks:
  install:
    desc: Build and start the Docker containers
    cmds:
      - task: bootstrap
      - task: ssl

  start:
    desc: Start the Docker containers
    cmds:
      - docker compose up -d

  stop:
    desc: Stop the Docker containers
    cmds:
      - docker compose down

  ssl:
    internal: true
    cmds:
      - mkcert -key-file certs/local-key.pem -cert-file certs/local-cert.pem *.app.localhost app.localhost
      - mkcert -install
    status:
      - test -f certs/local-cert.pem
      - test -f certs/local-key.pem

  bootstrap:
    cmds:
      - task: php:install
      - task: node:install
      - docker compose build
