version: '3'

tasks:
  certs:
    cmds:
      - mkcert -cert-file certs/local-cert.pem -key-file certs/local-key.pem "app.localhost" "*.app.localhost"
    status:
      - test -f certs/local-cert.pem
      - test -f certs/local-key.pem
  
  build:
    cmds:
      - docker compose build
  
  start:
    deps: [build,certs]
    cmds:
      - docker compose up --detach --remove-orphans

  stop:
    cmds:
      - docker compose down

  compile-back:
    cmds:
      - docker compose run --rm php console graphql:compile
    sources:
      - apps/api/Application/GraphQL/**/*.php
    generates:
      - apps/api/var/GraphQL/*.php
  
  compile-front:
    cmds:
      - docker compose run --rm frontend yarn graphql:generate
    sources:
      - apps/api/Application/GraphQL/**/*.php
    generates:
      - apps/frontend/src/graphql/index.ts
  
  compile:
    cmds:
      - task: compile-back
      - task: compile-front
  
  eslint:
    cmds:
      - docker compose run --rm frontend yarn eslint --fix

  jest:
    cmds:
      - docker compose run --rm frontend yarn test:spec
  
  php-cs-fixer:
    cmds:
      - docker compose run --rm php bin/php-cs-fixer fix

  phpstan:
    cmds:
      - docker compose run --rm php bin/phpstan analyse --level max public config src