version: '3'

silent: true
output: 'prefixed'

tasks:
  install:
    desc: Install backend dependencies
    cmds:
      - docker compose run --rm php composer install
    sources:
      - apps/api/composer.json
      - apps/api/composer.lock
  
  php-cs-fixer:
    desc: Enforce code style
    cmds:
      - docker compose run --rm php php-cs-fixer fix

  phpstan:
    desc: Static analysis
    cmds:
      - docker compose run --rm php phpstan analyse -c phpstan.neon

  deptrac:
    desc: Static analysis
    cmds:
      - docker compose run --rm php deptrac
  
  lint:
    desc: Enforce code style and analyse code
    cmds:
      - task: php-cs-fixer
      - task: phpstan
      - task: deptrac
