version: '3'

silent: true
output: 'prefixed'

includes:
  core: ./core.yaml

tasks:
  build:
    desc: Build container images
    cmds:
      - docker compose build

  start:
    desc: Start containers
    deps: [core:certs]
    cmds:
      - docker compose up --detach --remove-orphans

  stop:
    desc: Stop and remove containers
    cmds:
      - docker compose down
  
  restart:
    desc: Restart containers
    cmds:
      - task: stop
      - task: start

  run:frontend:
    desc: Run single command on frontend container
    cmds:
      - docker compose run --rm node {{.CLI_ARGS}}

  run:backend:
    desc: Run single command on backend container
    cmds:
      - docker compose run --rm php {{.CLI_ARGS}}
