version: '3'

silent: true
output: 'prefixed'

tasks:
  install:
    desc: Install frontend dependencies
    cmds:
      - docker compose run --rm frontend yarn install --pure-lockfile
    sources:
      - apps/frontend/package.json
      - apps/frontend/yarn.lock
    generates:
      - apps/frontend/node_modules/**/*

  compile:
    desc: Generate typed hooks
    cmds:
      - docker compose run --rm frontend yarn graphql:generate
    sources:
      - apps/api/Application/GraphQL/**/*.php
    generates:
      - apps/frontend/src/hooks/graphql.ts
  
  eslint:
    desc: Enforce code style
    cmds:
      - docker compose run --rm frontend yarn eslint --fix

  jest:
    desc: Run unit tests (Jest)
    cmds:
      - docker compose run --rm frontend yarn test:spec