overblog_graphql:
    definitions:
        use_classloader_listener: false
        auto_compile: true
        cache_dir: "%kernel.project_dir%/var/GraphQL"
        class_namespace: "Cache\\GraphQL\\__DEFINITIONS__"
        schema:
            query: Query
        mappings:
            types:
                -   type: attribute
                    dir: "%kernel.project_dir%/src/Application/GraphQL/Types"
                    suffix: null

                -   type: attribute
                    dir: "%kernel.project_dir%/src/Application/GraphQL/Resolver"
                    suffix: null
