parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    Application\GraphQL\Resolver\:
        public: true
        resource: '%kernel.project_dir%/src/Application/GraphQL/Resolver'
