doctrine_migrations:
    migrations_paths:
        'Infrastructure\Doctrine\Migrations': '%kernel.project_dir%/src/Infrastructure/Doctrine/Migrations'
    enable_profiler: false
    storage:
        table_storage:
            table_name: 'migration_version'
            version_column_name: 'version'
            executed_at_column_name: 'executed_at'
    all_or_nothing: true
    check_database_platform: true
