overblog_graphql:
    definitions:
        schema:
            # query: Query
            # mutation: Mutation
        mappings:
            types:
                - type: attribute
                  dir: '%kernel.project_dir%/src/Application/GraphQL/Type'

                - type: attribute
                  dir: '%kernel.project_dir%/src/Application/GraphQL/Resolver'

                - type: attribute
                  dir: '%kernel.project_dir%/src/Application/GraphQL/Query'

                - type: attribute
                  dir: '%kernel.project_dir%/src/Application/GraphQL/Mutation'
