framework:
    messenger:
        transports:
            async: '%env(resolve:MESSENGER_TRANSPORT_DSN)%'
            sync: 'sync://'

        default_bus: transactional.bus

        buses:
            transactional.bus:
                middleware:
                    - doctrine_transaction

            simple.bus:

        routing:
            Domain\Message\Command\CommandInterface: sync
            Domain\Message\Query\QueryInterface: sync
            Domain\Message\Event\EventInterface: async
