framework:
    messenger:
        transports:
            async: '%env(resolve:MESSENGER_TRANSPORT_DSN)%'
            sync: 'sync://'

        default_bus: command.bus

        buses:
            command.bus:
                middleware:
                    - add_bus_name_stamp_middleware
                    - doctrine_close_connection
                    - doctrine_transaction

            query.bus:
                middleware:
                    - add_bus_name_stamp_middleware
                    - doctrine_close_connection

            event.bus:
                default_middleware:
                    enabled: true
                    allow_no_handlers: true
                    allow_no_senders: true

        routing:
            Domain\Queue\Command\CommandInterface: sync
            Domain\Queue\Query\QueryInterface: sync
            Domain\Queue\Event\EventInterface: async

when@test:
   framework:
       messenger:
           transports:
               async: 'in-memory://'
