security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: Domain\Model\User
                property: email
    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            json_login:
                check_path: api_login
            logout:
                path: /api/logout

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
