name: API Code Quality

on:
  push:
    paths:
      - apps/api/**
      - .github/workflows/api.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  COMPOSE_FILE: docker-compose.test.yml

jobs:
  code_quality:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tool: [cs-fixer, phpstan, rector]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Initialize
        run: task init

      - name: Run ${{ matrix.tool }}
        run: task ${{ matrix.tool }}
