name: PHP Code Quality

on:
  push: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code_quality:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      pages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images
        run: docker compose -f docker-compose.tools.yml build

      - name: Install dependencies
        run: docker compose -f docker-compose.tools.yml run --entrypoint composer --rm composer install --no-scripts --ignore-platform-reqs --no-scripts --prefer-dist
      # cs-fixer, phpstan, deptrac, rector, phpspec\

      - name: Run PHP CS Fixer
        run: task cs-fixer

      - name: Run PHPStan
        run: task phpstan

      - name: Run Deptrac
        run: task deptrac

      - name: Run Rector
        run: task rector

      - name: Run PHP Spec
        run: task phpspec

      - name: Setup Pages
        if: github.ref == 'refs/heads/develop'
        uses: actions/configure-pages@v4

      - name: Upload coverages
        if: github.ref == 'refs/heads/develop'
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/api/coverage

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/develop'
        id: deployment
        uses: actions/deploy-pages@v4
