name: PHP Code Quality

on:
  push: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code_quality:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        command: [cs-fixer, phpstan, deptrac, rector]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.command }}
        run: docker compose -f docker-compose.tools.yml build composer ${{ matrix.command }}

      - name: Install dependencies
        run: docker compose -f docker-compose.tools.yml run --rm composer install --no-interaction --no-progress --no-suggest --no-scripts --prefer-dist

      - name: Run ${{ matrix.command }}
        run: task ${{ matrix.command }}
