on:
  pull_request:
    paths:
      - apps/api/*
      - .github/workflows/backend.yaml
    branches:
      - main
      - develop
  push:
    paths:
      - apps/api/*
      - .github/workflows/backend.yaml
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  hadolint:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: apps/api/Dockerfile

  docker:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export api image
        uses: docker/build-push-action@v6
        with:
          context: apps/api
          target: ${{ github.ref == 'refs/heads/develop' && 'base' || 'test' }}
          cache-from: type=gha,name=api:cache-latest
          cache-to: type=gha,mode=max,name=api:cache-${{ github.ref == 'refs/heads/develop' && 'latest' || github.sha }}

  backend:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        tool:
          - cs-check
          - phpstan
          - pest:unit
          - pest:feature

    needs: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare api image
        uses: docker/build-push-action@v6
        with:
          tags: api:test
          context: apps/api
          target: test
          cache-from: type=gha,name=api:cache-${{ github.ref == 'refs/heads/develop' && 'latest' || github.sha }}
          load: true

      - name: Run ${{ matrix.tool }}
        run: docker run --env-file apps/api/.env api:test composer ${{ matrix.tool }}
