name: Continuous integration

on:
  push: ~

jobs:
  should_skip_ci:
    runs-on: ubuntu-latest

    outputs:
      skip-api: ${{ steps.ssc-api.outputs.api }}
      skip-front: ${{ steps.ssc-front.outputs.front }}
      never-skip: ${{ steps.ssc-deploy.outputs.deploy }}
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Should skip CI
        run: "sudo curl -sSL -o /usr/local/bin/ssc https://github.com/KnpLabs/should-skip-ci/releases/download/v0.2.2/ssc-x86_64 && sudo chmod +x /usr/local/bin/ssc"
      
      - name: Should skip backend CI
        id: ssc-api
        run: ssc --path apps/api --base-branch develop --cmd "echo \"api=skip\" >> $GITHUB_OUTPUT"
      
      - name: Should skip frontend CI
        id: ssc-front
        run: ssc --path apps/frontend --base-branch develop --cmd "echo \"front=skip\" >> $GITHUB_OUTPUT"
  
  frontend:
    runs-on: ubuntu-latest
    needs:
      - should_skip_ci
    
    if: needs.should_skip_ci.outputs.skip-front != 'skip'
    
    steps:
      - uses: arduino/setup-task@v1
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install front stack
        run: task front:install
      - name: Ensure quality
        run: task front:lint
  
  backend:
    runs-on: ubuntu-latest
    needs:
      - should_skip_ci
    
    if: needs.should_skip_ci.outputs.skip-api != 'skip'
    
    steps:
      - uses: arduino/setup-task@v1
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install API stack
        run: task back:install
      - name: Ensure quality
        run: task back:lint
