name: Docker

on:
  push:
    paths:
      - '**/Dockerfile'
      - .github/workflows/docker.yaml

jobs:
  hadolint:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        dockerfile: [docker/api/Dockerfile, docker/web/Dockerfile]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: ${{ matrix.dockerfile }}
