on:
  pull_request:
    paths:
      - apps/web
      - .github/workflows/frontend.yaml
    branches:
      - main
      - develop
  push:
    paths:
      - apps/web
      - .github/workflows/frontend.yaml
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  COMPOSE_FILE: docker-compose.test.yml

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  hadolint:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: apps/web/Dockerfile

  docker:
    runs-on: ubuntu-24.04

    needs: hadolint

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and cache web image
        uses: docker/build-push-action@v6
        with:
          context: apps/web
          target: ${{ github.ref == 'refs/heads/develop' && 'base' || 'test' }}
          cache-from: type=gha,name=web:cache-latest
          cache-to: type=gha,mode=max,name=web:cache-${{ github.ref == 'refs/heads/develop' && 'latest' || github.sha }}

  frontend:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        tool: [eslint]

    env:
      COMPOSE_FILE: docker-compose.test.yml

    needs: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare web image
        uses: docker/build-push-action@v6
        with:
          tags: web:test
          context: apps/web
          target: test
          cache-from: type=gha,name=web:cache-${{ github.ref == 'refs/heads/develop' && 'latest' || github.sha }}
          load: true

      - name: Run ${{ matrix.tool }}
        run: docker run web:test yarn ${{ matrix.tool }}
