on:
  pull_request:
    paths:
      - services
      - .github/workflows/services.yaml
    branches:
      - main
      - develop
  push:
    paths:
      - services
      - .github/workflows/services.yaml
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hadolint:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        dockerfile:
          - services/mysql/Dockerfile
          - services/nginx/Dockerfile
          - services/rabbitmq/Dockerfile
          - services/traefik/Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: ${{ matrix.dockerfile }}
