name: Web Code Quality

on:
  push:
    paths:
      - apps/web/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code_quality:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      pages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Boostrap
        run: |
          cp apps/web/.env.dist apps/web/.env
          docker compose build node

      - name: Install dependencies
        run: task yarn_install

      - name: Run ES Lint
        run: task eslint
