name: Code Quality

on:
  push:
    paths:
      - apps/web/**
      - .github/workflows/web.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code_quality:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tool: [eslint]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Initialize
        run: task init

      - name: Run ${{ matrix.tool }}
        run: task node:${{ matrix.tool }}
